export const FETCH_ALL_CAPSULES_SUCCESS = 'FETCH_ALL_CAPSULES_SUCCESS';
export const FETCH_ALL_CAPSULES_FAILURE = 'FETCH_ALL_CAPSULES_FAILURE';
export const FETCH_LANDING_PAD_SUCCESS = 'FETCH_LANDING_PAD_SUCCESS';
export const FETCH_LANDING_PAD_FAILURE = 'FETCH_LANDING_PAD_FAILURE';
export const SHOW_INPROGRESS = 'SHOW_INPROGRESS';